# Generated by Django 4.2.2 on 2023-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='idUtilisateur',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
